version: '3.4'

services:
  mijnapp-backend:
    container_name: mijnapp-backend
    environment:
      - ASPNETCORE_ENVIRONMENT=Release
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_HTTPS_PORT=40443
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/app/cert/test.pfx
      - ASPNETCORE_Kestrel__Certificates__Default__Password=MyPassword
      - ORIGINS=http://localhost:60080
      - JwtClaimEncryption__SecretKey=1234567890ABCDEF
      - Jwt__Key=***REMOVED***
      - Jwt__Issuer=MijnApp
      - DigidCgi__SiamServer=https://alsiam.s-hertogenbosch.nl/aselectserver/server
      - DigidCgi__ApplicationId=Denbosch_Verhuizen
      - DigidCgi__SiamServerName=alsiam.s-hertogenbosch.nl
      - DigidCgi__CertificatePath=/app/cert/verhuizen.accp.s-hertogenbosch.nl.pfx
      - DigidCgi__CertificatePassword=***REMOVED***
      - HasFakeLoginEnabled=true
      - Api__AddressApiKey=***REMOVED***
      - Api__BrpApiKey=***REMOVED***
      - Api__OrderApiKey=***REMOVED***
      - Api__OrderTypeApiKey=***REMOVED***
      - Api__ProcessApiKey=***REMOVED***
      - Api__WebResourceApiKey=***REMOVED***
      - Api__ContractApiKey=aaaaaaaaaaaaaaaa
      - DigidCgi__SharedSecret=***REMOVED***
    ports:
      - "40080:80"
      - "40443:443"
      
  mijnapp-frontend:
    container_name: mijnapp-frontend
    environment:
      - ASPNETCORE_ENVIRONMENT=Release
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_HTTPS_PORT=60443
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/app/cert/test.pfx
      - ASPNETCORE_Kestrel__Certificates__Default__Password=MyPassword
      - PublicSettings__BACKEND_URL=http://localhost:40080
      - PublicSettings__HAS_FAKE_INLOG_ENABLED=true
    ports:
      - "60080:80"
      - "60443:443"
