version: '3.4'

services:
  mijnapp-backend:
    image: ${DOCKER_REGISTRY}/backend:${APP_ENV}
    build:
      context: .
      dockerfile: MijnApp-Backend/Dockerfile

  mijnapp-frontend:
    image: ${DOCKER_REGISTRY}/frontend:${APP_ENV}
    build:
      context: .
      dockerfile: MijnApp-Frontend/Dockerfile

