version: '3.4'

services:
  mijnapp-backend:
    image: ${DOCKER_REGISTRY-}mijnappbackend-${BRANCH_NAME}
    build:
      context: .
      dockerfile: MijnApp-Backend/Dockerfile

  mijnapp-frontend:
    image: ${DOCKER_REGISTRY-}mijnappfrontend-${BRANCH_NAME}
    build:
      context: .
      dockerfile: MijnApp-Frontend/Dockerfile

