version: '3.4'

services:
  mijnapp-backend:
    image: ${DOCKER_REGISTRY-}mijnappbackend
    build:
      context: .
      dockerfile: DockerfileBackend

  mijnapp-frontend:
    image: ${DOCKER_REGISTRY-}mijnappfrontend
    build:
      context: .
      dockerfile: DockerfileFrontend

