apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "name" . }}-backend
  labels:
    app.kubernetes.io/name: {{ include "name" . }}-backend
    app.kubernetes.io/part-of: {{ include "name" . }}
    helm.sh/chart: {{ include "chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "name" . }}-backend
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "name" . }}-backend
        app.kubernetes.io/part-of: {{ include "name" . }}
        helm.sh/chart: {{ include "chart" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/managed-by: {{ .Release.Service }}
    spec:
      containers:
        - name: {{ include "name" . }}-backend
          image: "docker.io/mijnapp/backend:{{ .Values.settings.env }}"
          imagePullPolicy: Always
          ports:
            - containerPort: 80
            - containerPort: 443
          env:
            # General settings
            - name: ASPNETCORE_ENVIRONMENT
              value: Release
            - name: ASPNETCORE_URLS
              value: https://+:443;http://+:80
            - name: ASPNETCORE_HTTPS_PORT
              value: '443'
            - name: ASPNETCORE_Kestrel__Certificates__Default__Path
              value: /app/cert/test.pfx
            - name: ORIGINS
              value: https://verhuizen.accp.s-hertogenbosch.nl/mijnapp-backend/
            - name: Jwt__Issuer
              valueFrom:
                configMapKeyRef:
                  name: {{ template "fullname" . }}
                  key: jwt-issuer
            - name: DigidCgi__SiamServer
              valueFrom:
                configMapKeyRef:
                  name: {{ template "fullname" . }}
                  key: digid-server
            - name: DigidCgi__ApplicationId
              valueFrom:
                configMapKeyRef:
                  name: {{ template "fullname" . }}
                  key: digid-application-id
            - name: DigidCgi__SiamServerName
              valueFrom:
                configMapKeyRef:
                  name: {{ template "fullname" . }}
                  key: digid-servername

            # API Uris
            - name: Api__AddressUri
              valueFrom:
                configMapKeyRef:
                  name: {{ template "fullname" . }}
                  key: address-endpoint
            - name: Api__BrpUri
              valueFrom:
                configMapKeyRef:
                  name: {{ template "fullname" . }}
                  key: brp-endpoint
            - name: Api__OrderUri
              valueFrom:
                configMapKeyRef:
                  name: {{ template "fullname" . }}
                  key: verzoeken-endpoint
            - name: Api__OrderTypeUri
              valueFrom:
                configMapKeyRef:
                  name: {{ template "fullname" . }}
                  key: verzoekType-endpoint
            - name: Api__ProcessUri
              valueFrom:
                configMapKeyRef:
                  name: {{ template "fullname" . }}
                  key: processType-endpoint
            - name: Api__WebResourceUri
              valueFrom:
                configMapKeyRef:
                  name: {{ template "fullname" . }}
                  key: webResource-endpoint
            - name: Api__ContractUri
              valueFrom:
                configMapKeyRef:
                  name: {{ template "fullname" . }}
                  key: contract-endpoint

            # Secret information
            - name: HasFakeLoginEnabled
              valueFrom:
                secretKeyRef:
                  name: {{ template "fullname" . }}
                  key: HasFakeLoginEnabled
            - name: Api__AddressApiKey
              valueFrom:
                secretKeyRef:
                  name: {{ template "fullname" . }}
                  key: AddressApiKey
            - name: Api__BrpApiKey
              valueFrom:
                secretKeyRef:
                  name: {{ template "fullname" . }}
                  key: BrpApiKey
            - name: Api__OrderApiKey
              valueFrom:
                secretKeyRef:
                  name: {{ template "fullname" . }}
                  key: OrderApiKey
            - name: Api__OrderTypeApiKey
              valueFrom:
                secretKeyRef:
                  name: {{ template "fullname" . }}
                  key: OrderTypeApiKey
            - name: Api__ProcessApiKey
              valueFrom:
                secretKeyRef:
                  name: {{ template "fullname" . }}
                  key: ProcessApiKey
            - name: Api__WebResourceApiKey
              valueFrom:
                secretKeyRef:
                  name: {{ template "fullname" . }}
                  key: WebResourceApiKey
            - name: Api__ContractApiKey
              valueFrom:
                secretKeyRef:
                  name: {{ template "fullname" . }}
                  key: ContractApiKey
            - name: DigidCgi__CertificatePath
              valueFrom:
                secretKeyRef:
                  name: {{ template "fullname" . }}
                  key: DigidCertPath
            - name: DigidCgi__CertificatePassword
              valueFrom:
                secretKeyRef:
                  name: {{ template "fullname" . }}
                  key: DigidCertPassword
            - name: DigidCgi__SharedSecret
              valueFrom:
                secretKeyRef:
                  name: {{template "fullname" . }}
                  key: DigidSharedSecret
            - name: Jwt__Key
              valueFrom:
                secretKeyRef:
                  name: {{template "fullname" . }}
                  key: JwtKey
            - name: JwtClaimEncryption__SecretKey
              valueFrom:
                secretKeyRef:
                  name: {{template "fullname" . }}
                  key: JwtClaimEncryptionSecretKey
            - name: ASPNETCORE_Kestrel__Certificates__Default__Password
              valueFrom:
                secretKeyRef:
                  name: {{template "fullname" . }}
                  key: AspNetCoreCertificatesDefaultPassword