apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: {{ include "name" . }}-{{ .Values.settings.env }}-cert
  labels:
    app.kubernetes.io/name: {{ include "name" . }}
    app.kubernetes.io/part-of: {{ include "name" . }}
    helm.sh/chart: {{ include "chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  secretName: {{ template "fullname" . }}
  duration: 24h
  renewBefore: 12h
  dnsNames:
  {{- if eq .Values.settings.env "release" }}
    - {{ .Values.settings.subdomain }}.{{ .Values.settings.domain }}
  {{- else }}
    - {{ .Values.settings.subdomain }}.{{ .Values.settings.env }}.{{ .Values.settings.domain }}
  {{- end }}
#{{- range  .Values.settings.domains  }}
#  {{- if eq $.Values.settings.env "prod" }}
#    - {{ $.Values.settings.name }}.{{ . }}
#  {{- else }}
#  - {{ $.Values.settings.name }}.{{ $.Values.settings.env }}.{{ . }}
#  {{- end }}
#{{- end }}
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer