apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "fullname" . }}
  #namespace: {{ .Values.settings.env }}
  labels:
    app.kubernetes.io/name: {{ include "name" . }}
    app.kubernetes.io/part-of: {{ include "name" . }}
    helm.sh/chart: {{ include "chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
  adres-endpoint: {{ .Values.settings.adresEndpoint | quote }}
  order-endpoint: {{ .Values.settings.orderEndpoint | quote }}
  brp-endpoint: {{ .Values.settings.brpEndpoint | quote }}
  verzoeken-endpoint: {{ .Values.settings.verzoekenEndpoint | quote }}
  verzoekType-endpoint: {{ .Values.settings.verzoekTypeEndpoint | quote }}
  processType-endpoint: {{ .Values.settings.processTypeEndpoint | quote }}
