apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    # add an annotation indicating the issuer to use.
    cert-manager.io/acme-challenge-type: http01
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/rewrite-target: /$1
  name: {{ include "name" . }}-{{ .Values.settings.env }}-ingress
  labels:
    app.kubernetes.io/name: {{ include "name" . }}-ingress
    app.kubernetes.io/part-of: {{ include "name" . }}
    helm.sh/chart: {{ include "chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  tls: 
  - hosts: 
    - {{ $.Values.settings.domain }}
    secretName: {{ template "fullname" . }}
  rules:
    {{- if and (eq $.Values.settings.env "release") $.Values.settings.subdomain }}

    - host: {{ $.Values.settings.subdomain }}.{{ $.Values.settings.domain }}
      http:
        paths:
          - path: /mijnapp-backend/(.*)
            backend:
              serviceName: {{ include "name" . }}-backend
              servicePort: 80
          - path: /(.*)
            backend:
              serviceName: {{ include "name" . }}
              servicePort: 80
    {{- else if eq $.Values.settings.env "release" }}
    - host: {{ $.Values.settings.domain }}
      http:
        paths:
          - path: /mijnapp-backend/(.*)
            backend:
              serviceName: {{ include "name" . }}-backend
              servicePort: 80
          - path: /(.*)
            backend:
              serviceName: {{ include "name" . }}
              servicePort: 80
    - host: www.{{ $.Values.settings.domain }}
      http:
        paths:
          - path: /mijnapp-backend/(.*)
            backend:
              serviceName: {{ include "name" . }}-backend
              servicePort: 80
          - path: /(.*)
            backend:
              serviceName: {{ include "name" . }}
              servicePort: 80
    {{- else }}
    - host: {{ $.Values.settings.subdomain }}.{{ $.Values.settings.env }}.{{ $.Values.settings.domain }}
      http:
        paths:
            - path: /mijnapp-backend/(.*)
              backend:
                serviceName: {{ include "name" . }}-backend
                servicePort: 80
              - path: /(.*)
                backend:
                  serviceName: {{ include "name" . }}
                  servicePort: 80
    {{- end }}
