{{- $postgresqlServiceName := include "postgresql.fullname" . -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "name" . }}
    app.kubernetes.io/part-of: {{ include "name" . }}
    helm.sh/chart: {{ include "chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: Opaque
data:
  HasFakeLoginEnabled: {{ .Values.settings.HasFakeLoginEnabled | quote | b64enc }}
  AddressApiKey: {{ .Values.security.commonGroundKey | b64enc }}
  BrpApiKey: {{ .Values.security.commonGroundKey | b64enc }}
  OrderApiKey: {{ .Values.security.commonGroundKey | b64enc }}
  OrderTypeApiKey: {{ .Values.security.commonGroundKey | b64enc }}
  ProcessApiKey: {{ .Values.security.commonGroundKey | b64enc }}
  WebResourceApiKey: {{ .Values.security.commonGroundKey | b64enc }}
  ContractApiKey: {{ .Values.security.contractKey | b64enc }}
  DigidSharedSecret: {{ .Values.security.digidSharedSecret | b64enc }}
  DigidCertPath: {{ .Values.security.digidCertPath | b64enc }}
  DigidCertPassword: {{ .Values.security.digidCertPass | b64enc }}
  JwtKey: {{ .Values.security.jwtKey | b64enc }}
  JwtClaimEncryptionSecretKey: {{ .Values.security.jwtEncryptionKey | b64enc }}
  AspNetCoreCertificatesDefaultPassword: {{ .Values.security.defaultPass | b64enc }}
