{{- $postgresqlServiceName := include "postgresql.fullname" . -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "name" . }}
    app.kubernetes.io/part-of: {{ include "name" . }}
    helm.sh/chart: {{ include "chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: Opaque
data:
  HasFakeLoginEnabled: {{ .Values.settings.HasFakeLoginEnabled | quote }}
  AddressApiKey: !changeMe!
  BrpApiKey: !changeMe!
  OrderApiKey: !changeMe!
  OrderTypeApiKey: !changeMe!
  ProcessApiKey: !changeMe!
  WebResourceApiKey: !changeMe!
  ContractApiKey: aaaaaaaaaaaaa
  DigidSharedSecret: !changeMe!
  DigidCertPath: /app/cert/verhuizen.accp.s-hertogenbosch.nl.pfx
  DigidCertPassword: ***REMOVED***
  JwtKey: !changeMe!
  JwtClaimEncryptionSecretKey: 1234567890ABCDEF
  AspNetCoreCertificatesDefaultPassword: MyPassword
