{{- $postgresqlServiceName := include "postgresql.fullname" . -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "name" . }}
    app.kubernetes.io/part-of: {{ include "name" . }}
    helm.sh/chart: {{ include "chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: Opaque
data:
  HasFakeLoginEnabled: {{ .Values.settings.HasFakeLoginEnabled | quote }}
  AddressApiKey: ***REMOVED***
  BrpApiKey: ***REMOVED***
  OrderApiKey: ***REMOVED***
  OrderTypeApiKey: ***REMOVED***
  ProcessApiKey: ***REMOVED***
  WebResourceApiKey: ***REMOVED***
